# Generated by Django 4.2.7 on 2024-02-02 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_antrenor_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antrenor',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='antrenor',
            name='description',
        ),
    ]
