# Generated by Django 4.2.7 on 2024-02-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_fiyatlar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fiyatlar',
            old_name='name',
            new_name='ay',
        ),
        migrations.AddField(
            model_name='fiyatlar',
            name='paket',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
