# Generated by Django 4.2.7 on 2024-02-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_name_fiyatlar_ay_fiyatlar_paket'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiyatlar',
            name='odeme_sekli',
            field=models.CharField(choices=[('Nakit', 'Nakit'), ('KREDI KARTI', 'KREDI KARTI')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
