# Generated by Django 5.0.1 on 2024-02-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_fiyatlar_odeme_sekli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiyatlar',
            name='odeme_sekli',
            field=models.CharField(choices=[('NAKIT', 'NAKIT'), ('KREDI KARTI', 'KREDI KARTI')], max_length=20),
        ),
    ]
