# Generated by Django 5.0.1 on 2024-02-17 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_antrenor_instagram'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antrenor',
            old_name='instagram',
            new_name='instagram_Kullanici_Adi',
        ),
    ]
