# Generated by Django 5.0.1 on 2024-02-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_antrenor_instagram_kullanici_adi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antrenor',
            name='instagram_kullanici_adi',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
